// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace HelloForm
{
	public partial class Form1 : NSViewController
	{
		public Form1 (IntPtr handle) : base (handle)
		{
		}

		partial void button1_click(AppKit.NSButton sender) {
			Lable1.StringValue = "hello I am a CS student.";

		}
	}
}
